#!/usr/bin/env python3
"""Generate realistic example responses from actual Lineage MCP server functions.

This script imports the server module and calls real async tool functions to generate
authentic example outputs. All 6 tools are exercised with real data.

Output is normalized to replace temp paths with a placeholder and remove timestamps
to ensure consistent output across runs for version control.
"""

import asyncio
import re
import tempfile
import time
from pathlib import Path


def normalize_output(text: str, base_path: Path) -> str:
    """Normalize output by replacing temp paths and timestamps with placeholders.

    Args:
        text: Raw output from tool functions.
        base_path: The temp directory path to replace.

    Returns:
        Normalized output with stable paths and timestamps.
    """
    # Replace the absolute temp path with a placeholder
    # Handle both forward and backslash separators
    base_str = str(base_path)
    text = text.replace(base_str, "/workspace")
    text = text.replace(base_str.replace("\\", "/"), "/workspace")

    # Normalize backslashes in remaining paths
    text = text.replace("\\", "/")

    # Replace timestamps like "(0.10s ago)" or "(1s ago)" with placeholder
    text = re.sub(r"\(\d+\.?\d*s ago\)", "(Xs ago)", text)

    return text


async def generate_example_responses() -> str:
    """Generate example responses using actual server tool functions.

    Creates temporary directory structures and calls the actual server
    tool functions to generate real responses. Output is normalized
    to ensure consistent results across runs.

    Returns:
        String containing formatted example responses
    """
    examples = []

    # Add header
    examples.append("=" * 80)
    examples.append("LINEAGE MCP - COMPREHENSIVE TOOL EXAMPLES")
    examples.append("Generated by running actual server tool functions")
    examples.append("=" * 80)
    examples.append("")

    # Add parent directory to path to import server modules
    import sys
    parent_dir = Path(__file__).parent.parent.resolve()
    if str(parent_dir) not in sys.path:
        sys.path.insert(0, str(parent_dir))

    # Import server module functions and state
    import path_utils
    from config import INSTRUCTION_FILE_NAMES
    from tools import delete_file, edit_file, list_files, read_file, search_files, write_file, clear_cache
    from session_state import session

    # Create a comprehensive test directory
    with tempfile.TemporaryDirectory() as tmpdir:
        tmpdir_path = Path(tmpdir)

        # Set BASE_DIR to our temp directory
        old_base_dir = path_utils._base_dir
        path_utils._base_dir = tmpdir_path

        try:
            # Create directory structure
            src_dir = tmpdir_path / "src"
            app_dir = src_dir / "app"
            api_dir = src_dir / "api"
            app_dir.mkdir(parents=True)
            api_dir.mkdir(parents=True)

            # Create instruction files (AGENTS.md)
            root_agents = tmpdir_path / "AGENTS.md"
            root_agents.write_text(
                "# Project AGENTS.md\n\n"
                "## Global Instructions\n"
                "- Follow DDD principles\n"
                "- Use Result<T> pattern\n"
            )

            src_agents = src_dir / "AGENTS.md"
            src_agents.write_text(
                "# Source AGENTS.md\n\n"
                "## Source-specific rules\n"
                "- TypeScript for frontend\n"
                "- .NET for backend\n"
            )

            # Create a CLAUDE.md in api folder to test priority order
            api_claude = api_dir / "CLAUDE.md"
            api_claude.write_text(
                "# API CLAUDE.md\n\n"
                "## Claude-specific instructions\n"
                "- Use async/await patterns\n"
            )

            # Create various test files
            test_files = {
                "README.md": "# Test Project\n\nThis is a test project.",
                "config.json": '{\n    "debug": false,\n    "timeout": 30\n}',
                "src/app/page.tsx": "export default function Page() {\n    return <div>Hello</div>;\n}",
                "src/app/layout.tsx": "export default function Layout({ children }) {\n    return <html>{children}</html>;\n}",
                "src/api/handler.ts": "export async function handler(req) {\n    return Response.json({ok: true});\n}",
                "src/api/types.ts": "export type User = { id: number; name: string; };",
            }

            for rel_path, content in test_files.items():
                full_path = tmpdir_path / rel_path
                full_path.parent.mkdir(parents=True, exist_ok=True)
                full_path.write_text(content)

            # ================================================================
            # TOOL 1: list_files
            # ================================================================
            examples.append("=" * 80)
            examples.append("TOOL 1: list_files(path)")
            examples.append("=" * 80)
            examples.append("")

            examples.append(">>> list_files('')  # List root directory")
            examples.append("")
            result = await list_files("")
            examples.append(result)
            examples.append("")

            examples.append(">>> list_files('src')  # List subdirectory")
            examples.append("")
            result = await list_files("src")
            examples.append(result)
            examples.append("")

            examples.append(">>> list_files('src/app')  # List nested directory")
            examples.append("")
            result = await list_files("src/app")
            examples.append(result)
            examples.append("")

            # ================================================================
            # TOOL 2: search_files
            # ================================================================
            examples.append("=" * 80)
            examples.append("TOOL 2: search_files(pattern, path)")
            examples.append("=" * 80)
            examples.append("")

            examples.append(">>> search_files('*.tsx')  # Find TypeScript React files")
            examples.append("")
            result = await search_files("*.tsx")
            examples.append(result)
            examples.append("")

            examples.append(">>> search_files('**/*.ts')  # Recursive search for .ts files")
            examples.append("")
            result = await search_files("**/*.ts")
            examples.append(result)
            examples.append("")

            examples.append(">>> search_files('*.md', path='src')  # Search in subdirectory")
            examples.append("")
            result = await search_files("*.md", path="src")
            examples.append(result)
            examples.append("")

            examples.append(">>> search_files('*.nonexistent')  # No matches")
            examples.append("")
            result = await search_files("*.nonexistent")
            examples.append(result)
            examples.append("")

            # ================================================================
            # TOOL 3: read_file (basic)
            # ================================================================
            examples.append("=" * 80)
            examples.append("TOOL 3: read_file(file_path, show_line_numbers, offset, limit)")
            examples.append("=" * 80)
            examples.append("")

            # Clear caches for fresh start
            session.clear()

            examples.append(">>> read_file('README.md')  # Basic read")
            examples.append("")
            result = await read_file("README.md")
            examples.append(result)
            examples.append("")

            examples.append(">>> read_file('config.json', show_line_numbers=True)  # With line numbers")
            examples.append("")
            result = await read_file("config.json", show_line_numbers=True)
            examples.append(result)
            examples.append("")

            # Test instruction file discovery
            examples.append(">>> read_file('src/app/page.tsx')  # Discovers parent instruction files")
            examples.append("")
            result = await read_file("src/app/page.tsx")
            examples.append(result)
            examples.append("")

            # Test reading instruction file directly (should add folder to provided cache)
            examples.append(">>> read_file('src/AGENTS.md')  # Direct instruction file read")
            examples.append("")
            result = await read_file("src/AGENTS.md")
            examples.append(result)
            examples.append("")

            # Read another file - src folder instruction file should NOT be re-appended
            examples.append(">>> read_file('src/api/handler.ts')  # Instruction files not re-appended")
            examples.append("")
            result = await read_file("src/api/handler.ts")
            examples.append(result)
            examples.append("")

            # Test priority order - api folder has CLAUDE.md (should be picked over AGENTS.md)
            # Reset caches to see the instruction file again
            session.provided_folders.clear()
            examples.append(">>> read_file('src/api/types.ts')  # CLAUDE.md is higher priority in api folder")
            examples.append("")
            result = await read_file("src/api/types.ts")
            examples.append(result)
            examples.append("")

            # ================================================================
            # TOOL 3 (continued): read_file with offset/limit
            # ================================================================
            examples.append("-" * 80)
            examples.append("read_file with offset/limit (partial reads)")
            examples.append("-" * 80)
            examples.append("")

            # Create a file with many lines for partial read testing
            multiline_file = tmpdir_path / "multiline.txt"
            with multiline_file.open("w") as f:
                for i in range(1, 21):
                    f.write(f"Line {i}: This is content for line {i}\n")

            examples.append(">>> read_file('multiline.txt', offset=5, limit=5)  # Lines 6-10")
            examples.append("")
            result = await read_file("multiline.txt", offset=5, limit=5)
            examples.append(result)
            examples.append("")

            examples.append(">>> read_file('multiline.txt', offset=5, limit=5, show_line_numbers=True)")
            examples.append("")
            result = await read_file("multiline.txt", offset=5, limit=5, show_line_numbers=True)
            examples.append(result)
            examples.append("")

            examples.append(">>> read_file('multiline.txt', offset=100)  # Offset beyond EOF")
            examples.append("")
            result = await read_file("multiline.txt", offset=100)
            examples.append(result)
            examples.append("")

            # ================================================================
            # TOOL 4: write_file
            # ================================================================
            examples.append("=" * 80)
            examples.append("TOOL 4: write_file(file_path, content)")
            examples.append("=" * 80)
            examples.append("")

            examples.append(">>> write_file('new_file.txt', 'Hello, World!')  # Create new file")
            examples.append("")
            result = await write_file("new_file.txt", "Hello, World!")
            examples.append(result)
            examples.append("")

            examples.append(">>> write_file('src/app/new_component.tsx', 'export default () => <div>New!</div>;')")
            examples.append("")
            result = await write_file("src/app/new_component.tsx", "export default () => <div>New!</div>;")
            examples.append(result)
            examples.append("")

            # Verify file was created
            examples.append(">>> read_file('new_file.txt')  # Verify write")
            examples.append("")
            result = await read_file("new_file.txt")
            examples.append(result)
            examples.append("")

            # ================================================================
            # TOOL 5: edit_file
            # ================================================================
            examples.append("=" * 80)
            examples.append("TOOL 5: edit_file(file_path, old_string, new_string, replace_all)")
            examples.append("=" * 80)
            examples.append("")

            # Create a file to edit
            edit_test_file = tmpdir_path / "edit_test.py"
            edit_test_file.write_text(
                "def hello():\n"
                "    return 'hello'\n"
                "\n"
                "def world():\n"
                "    return 'world'\n"
            )

            examples.append(">>> edit_file('edit_test.py', \"return 'hello'\", \"return 'HELLO'\")")
            examples.append("")
            result = await edit_file("edit_test.py", "return 'hello'", "return 'HELLO'")
            examples.append(result)
            examples.append("")

            # Test replace_all
            replace_all_file = tmpdir_path / "replace_all_test.txt"
            replace_all_file.write_text("foo bar foo baz foo\nfoo is repeated foo\n")

            examples.append(">>> edit_file('replace_all_test.txt', 'foo', 'FOO', replace_all=True)")
            examples.append("")
            result = await edit_file("replace_all_test.txt", "foo", "FOO", replace_all=True)
            examples.append(result)
            examples.append("")

            # Test error case - string not found
            examples.append(">>> edit_file('edit_test.py', 'nonexistent', 'replacement')  # Error case")
            examples.append("")
            result = await edit_file("edit_test.py", "nonexistent", "replacement")
            examples.append(result)
            examples.append("")

            # ================================================================
            # TOOL 6: delete_file
            # ================================================================
            examples.append("=" * 80)
            examples.append("TOOL 6: delete_file(file_path)")
            examples.append("=" * 80)
            examples.append("")

            # Create a file to delete
            delete_test_file = tmpdir_path / "to_delete.txt"
            delete_test_file.write_text("This file will be deleted")

            examples.append(">>> delete_file('to_delete.txt')  # Delete file")
            examples.append("")
            result = await delete_file("to_delete.txt")
            examples.append(result)
            examples.append("")

            # Create and delete empty directory
            empty_dir = tmpdir_path / "empty_dir"
            empty_dir.mkdir()

            examples.append(">>> delete_file('empty_dir')  # Delete empty directory")
            examples.append("")
            result = await delete_file("empty_dir")
            examples.append(result)
            examples.append("")

            # Test error case - file doesn't exist
            examples.append(">>> delete_file('nonexistent.txt')  # Error case")
            examples.append("")
            result = await delete_file("nonexistent.txt")
            examples.append(result)
            examples.append("")

            # ================================================================
            # CHANGE DETECTION DEMO
            # ================================================================
            examples.append("=" * 80)
            examples.append("CHANGE DETECTION DEMO")
            examples.append("=" * 80)
            examples.append("")

            # Clear caches
            session.clear()

            # Create and read a file
            change_test_file = tmpdir_path / "change_test.txt"
            change_test_file.write_text("Original content line 1\nOriginal content line 2\n")

            examples.append(">>> read_file('change_test.txt')  # First read - track file")
            examples.append("")
            result = await read_file("change_test.txt")
            examples.append(result)
            examples.append("")

            # Simulate external modification
            time.sleep(0.1)  # Ensure mtime changes
            change_test_file.write_text("Modified content line 1\nOriginal content line 2\nNew line 3\n")

            # Read another file - should see change
            examples.append(">>> list_files('')  # External change detected")
            examples.append("")
            result = await list_files("")
            examples.append(result)
            examples.append("")

            # ================================================================
            # clear() DEMO
            # ================================================================
            examples.append("=" * 80)
            examples.append("clear() DEMO")
            examples.append("=" * 80)
            examples.append("")

            # Demonstrate clear() tool
            examples.append(">>> clear_cache()  # Clears all session caches")
            examples.append("")
            result = await clear_cache()
            examples.append(result)
            examples.append("")

            # ================================================================
            # ERROR HANDLING DEMO
            # ================================================================
            examples.append("=" * 80)
            examples.append("ERROR HANDLING DEMO")
            examples.append("=" * 80)
            examples.append("")

            examples.append(">>> read_file('../../../etc/passwd')  # Directory traversal blocked")
            examples.append("")
            result = await read_file("../../../etc/passwd")
            examples.append(result)
            examples.append("")

            examples.append(">>> search_files('*.py', path='../../')  # Traversal in path blocked")
            examples.append("")
            result = await search_files("*.py", path="../../")
            examples.append(result)
            examples.append("")

            examples.append(">>> read_file('nonexistent_file.txt')  # File not found")
            examples.append("")
            result = await read_file("nonexistent_file.txt")
            examples.append(result)
            examples.append("")

            examples.append(">>> read_file('README.md', offset=-1)  # Invalid offset")
            examples.append("")
            result = await read_file("README.md", offset=-1)
            examples.append(result)
            examples.append("")

        finally:
            path_utils._base_dir = old_base_dir
            session.clear()

        # Normalize output to replace temp paths and timestamps
        raw_output = "\n".join(examples)
        normalized = normalize_output(raw_output, tmpdir_path)
        examples = [normalized]

    # ================================================================
    # SUMMARY
    # ================================================================
    examples.append("=" * 80)
    examples.append("SUMMARY - ALL 7 TOOLS TESTED")
    examples.append("=" * 80)
    examples.append("")
    examples.append("1. list_files(path) - Directory listing with markdown table")
    examples.append("2. search_files(pattern, path) - Glob pattern file search")
    examples.append("3. read_file(file_path, show_line_numbers, offset, limit)")
    examples.append("   - Full and partial reads")
    examples.append("   - Line number formatting")
    examples.append("   - Instruction file discovery (AGENTS.md, CLAUDE.md, etc.)")
    examples.append("   - Change detection")
    examples.append("4. write_file(file_path, content) - Create/overwrite files")
    examples.append("5. edit_file(file_path, old_string, new_string, replace_all) - String replacement")
    examples.append("6. delete_file(file_path) - Delete files and empty directories")
    examples.append("7. clear_cache() - Clear all session caches")
    examples.append("")
    examples.append("Cache is cleared via the system tray or precompact hooks, or explicitly via clear_cache().")
    examples.append("All tools include [CHANGED_FILES] section when external changes are detected.")
    examples.append("Changes are only reported once, then cache is updated.")
    examples.append("Instruction files shown once per folder per session (clear() resets).")
    examples.append(f"Configured instruction file names: {INSTRUCTION_FILE_NAMES}")
    examples.append("")

    return "\n".join(examples)


if __name__ == "__main__":
    # Generate examples using actual server functions
    examples_content = asyncio.run(generate_example_responses())

    # Get the directory of this script
    script_dir = Path(__file__).parent.resolve()
    output_file = script_dir / "example_responses.txt"

    # Write to file
    output_file.write_text(examples_content, encoding="utf-8")

    print(f"✅ Examples written to: {output_file}")
    print(f"✅ File size: {output_file.stat().st_size} bytes")
    print("✅ Generated by running actual server tool functions")
    print("")
    print("All 7 tools tested:")
    print("  1. list_files(path)")
    print("  2. search_files(pattern, path)")
    print("  3. read_file(file_path, show_line_numbers, offset, limit)")
    print("  4. write_file(file_path, content)")
    print("  5. edit_file(file_path, old_string, new_string, replace_all)")
    print("  6. delete_file(file_path)")
    print("  7. clear_cache()")
